#pragma once
#include "GameNode.h"
#include "Button.h"

#define WIDTH	180
#define HEIGHT	50

#define INTERVAL_X	30
#define INTERVAL_Y	20

#define REPORT_START_X		115
#define REPORT_START_Y		100

#define EXAMPLE_START_X		115
#define EXAMPLE_START_Y		550



enum SCENE_INDEX : int
{
	REPORT_CARD_MATCH, REPORT_MOLE, REPORT_CLAYSHOOTING, REPORT_AVOID,
	REPORT_BULLET_SHOOTING, REPORT_CROCODILE, REPORT_VERTICAL_SHOOTING, REPORT_HORIZONTAL_SHOOTING,
	REPORT_MOLE_IMAGE, REPORT_ANALOG_CLOCK, REPORT_SHELL_FIRE, REPORT_BULLET_GRAVITY,
	REPORT_SLICE_GAME, REPORT_MINI_MAP, REPORT_WORM_GAME, REPORT_ATTACK_COMBO,
	REPORT_MOTION_ANIMATION, REPORT_WALL_CATCH, REPORT_RACING_GAME, REPORT_BLACK_HOLE,
	REPORT_ATTACK_DEFENSE, REPORT_3D_MATRIX, REPORT_TILEMAP,

	REPORT_END,

	EXAMPLE_MOLE = REPORT_END,
	EXAMPLE_BULLET, EXAMPLE_MATH, EXAMPLE_IMAGE,
	EXAMPLE_CLIPING, EXAMPLE_FRAME_IMAGE, EXAMPLE_LOOP_RENDER,
	EXAMPLE_TEMP_SOUND, EAMPLE_SHOOTING_GAME, EXAMPLE_TENGAI, EXAMPLE_ANIMATION,

	SCENE_END, TITLE_SCENE
};

class TitleScene : public GameNode
{
private:
	vector<Button> _vSceneBtn;
	vector<Button>::iterator _viSceneBtn;

public:
	HRESULT init(void);
	void release(void);
	void update(void);
	void render(void);

	static void testFunc(string sceneName);

	TitleScene() {}
	~TitleScene() {}
};

